@echo off / "begin"
dsadd user "cn=pxzx001,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx002,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx003,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx004,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx005,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx006,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx007,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx008,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx009,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx010,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx011,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx012,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx013,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx014,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx015,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx016,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx017,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx018,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx019,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx020,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx021,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx022,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx023,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx024,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx025,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx026,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx027,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx028,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx029,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx030,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx031,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx032,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx033,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx034,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx035,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx036,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx037,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx038,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx039,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx040,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx041,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx042,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx043,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx044,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx045,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx046,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx047,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx048,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx049,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx050,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx051,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx052,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx053,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx054,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx055,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx056,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx057,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx058,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx059,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx060,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx061,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx062,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx063,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx064,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx065,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx066,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx067,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx068,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx069,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx070,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx071,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx072,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx073,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx074,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx075,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx076,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx077,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx078,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx079,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx080,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx081,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx082,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx083,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx084,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx085,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx086,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx087,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx088,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx089,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx090,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx091,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx092,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx093,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx094,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx095,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx096,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx097,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx098,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx099,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
dsadd user "cn=pxzx100,OU=培训中心桌面账户,OU=珠海鸡公山培训中心,OU=09 珠海石油分公司,ou=GDSY,ou=组织机构,dc=sinopec,dc=ad" -pwd pxzx0000 -canchpwd no -pwdneverexpires yes
pause
