SET CURSOR_CLOSE_ON_COMMIT ON		--设置为ON时,下面的代码报错
--SET CURSOR_CLOSE_ON_COMMIT OFF	--设置为OFF(默认值时),下面的代码正常

BEGIN TRAN

DECLARE CUR_tb CURSOR LOCAL
FOR
SELECT id = 1
OPEN CUR_tb
DECLARE @id int
FETCH CUR_tb INTO @id
WHILE @@FETCH_STATUS = 0
BEGIN
	COMMIT TRAN
	FETCH CUR_tb INTO @id
END
CLOSE CUR_tb
DEALLOCATE CUR_tb
